### PR TITLE
Improved implementation for RavenDB

### PR DESCRIPTION
**Pull request by xinix00**
- Locking jobs by entity itself (using RavenDB), skipping DistributedLocks (improves performance)
- Other way of locking (DistributedLocks), excluded jobs from this meganism
- Listen to changes in Queue, so it directly fetch the job
```c#
// Listen to the queues you actually use, else it fetches more than needed.
var options = new RavenStorageOptions()
{
   QueueNames = new[]
   {
      "listen_to_this_queue"
   }
};
GlobalConfiguration.Configuration.UseRavenStorage("http://ipaddress", "RavenDatabase", options);
```
- Improved entities, storing all (related) data inside one document (it's a document store!)
- Implemented RavenStorageMonitorApi, so you can finally use the dashboard
- Removed ExpirationManager, using RavenDB expiration plugin. No need for querying every once in a while to remove expired stuff
- Rewritten RavenWriteOnlyTransaction, to use a session, and save all in one go. Throws an exception when changed by someone else, which is supported by Hangfire, which will try it again later on.
- Changed the repository and the way it's working, to better follow the RavenDB workflow

**Please be carefull:**
- Database should use the Expiration plugin!
- Removed Dewey, makes no sense in Hangfire.Raven itself
- Removed references to RavenDB Server, only RavenDB.Client is required
- Removed references to Hangfire, only Hangfire.Core is required

### CODE REVIEW

**Comment by AustinWinstanley** [comment]
Nice. Has this been tested thoroughly? I am out of town right now and not able to test this myself. Can you confirm you've tested these changes well and used them?

**Comment by xinix00** [comment]
I did test it, though you have to take a look at the embedded store and the
dependency paths inside the solution file of hangfire.raven. My packages
from nuget are 2 levels deeper (using it as submodule (in git) inside
another project).

Also did not check the included example.

Running over a week now in a production environment, tested > 1,000,000
jobs.

Op vr 19 aug. 2016 17:33 schreef Austin Winstanley <notifications@github.com

**Comment by xinix00** [comment]
Added a new commit finetuning jobdata inside the document:
```json
{
    "Job": {
        "Arguments": [
            {
                "$type": "Beta.Core.Import.EktExportJobContext, Beta.Core.Import",
                "Name": "EktExportPreOrder"
            }
        ],
        "Type": "Beta.Core.Import.Jobs.HangfireEktExportPreOrderJob, Beta.Core.Import, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null",
        "Method": "Beta.Core.Import;Beta.Core.Import.Jobs.HangfireEktExportPreOrderJob;Execute"
    },
    "Parameters": {
        "RecurringJobId": "\"Name|EktExportPreOrder\"",
        "CurrentCulture": "\"en-US\"",
        "CurrentUICulture": "\"en-US\""
    },
    "CreatedAt": "2016-08-21T21:25:00.4575755Z",
    "StateData": {
        "Name": "Succeeded",
        "Reason": null,
        "Data": {
            "SucceededAt": "2016-08-21T21:25:00.5668436Z",
            "PerformanceDuration": "62",
            "Latency": "46"
        }
    },
    "History": [
        {
            "StateName": "Succeeded",
            "Reason": null,
            "CreatedAt": "2016-08-21T21:25:00.6138186Z",
            "Data": {
                "SucceededAt": "2016-08-21T21:25:00.5668436Z",
                "PerformanceDuration": "62",
                "Latency": "46"
            }
        },
        {
            "StateName": "Processing",
            "Reason": null,
            "CreatedAt": "2016-08-21T21:25:00.4888510Z",
            "Data": {
                "StartedAt": "2016-08-21T21:25:00.4888510Z",
                "ServerId": "ww01-tilaa-ams:2620:c71d3fba-eb5d-4e90-9446-b16a905cbaae",
                "WorkerId": "ad2596dd-90ed-4f77-a10b-b74e929386a8"
            }
        },
        {
            "StateName": "Enqueued",
            "Reason": "Triggered by recurring job scheduler",
            "CreatedAt": "2016-08-21T21:25:00.4731037Z",
            "Data": {
                "EnqueuedAt": "2016-08-21T21:25:00.3949318Z",
                "Queue": "ekt_export_preorder"
            }
        }
    ]
}
```
Have to take a look at the serialized parameters, to make it final. Any idea which service is using "List"? It's the only unoptimized bit. Rewritten "Hash" / "Sets" / "Counters" / "Job" to better accomodate the use of RavenDB.

**Comment by Sphiecoh** [comment]
How far along is the testing of this ?

**Comment by Sphiecoh** [comment]
build to nuget ?

**Comment by AustinWinstanley** [comment]
Built with these changes and .Net Core support and pushed to Nuget

https://www.nuget.org/packages/Hangfire.Raven/2.0.0

**Pull request merged**
